### PR TITLE
Add information about the tokens

### PR DESCRIPTION
**Pull request by danielfdsilva**

### CODE REVIEW

**Comment by smit1678** [comment]
👍 I'm going to add in small snippet with some sample code to populate the mongodb with a sample token to get up and running quickly. Then I think this is good to go.

**Comment by smit1678** [comment]
@danielfdsilva Other item is the newrelic.js license key: https://github.com/hotosm/oam-uploader-api/blob/feature/improve-readme/newrelic.js#L15. This raises an error if not filled in. Can we add a note about the requirement and that it could be removed if not needed?

**Comment by olafveerman** [comment]
Capturing notes from Slack convo. We should:

- move the New Relic license key to `local.env`, keeping everything centralized
- improve the docs of the env variables. There are discrepancies between `local.sample.env` and the Readme. Descriptions could also be better

cc @danielfdsilva

**Comment by smit1678** [comment]
👍

**Pull request merged**
